---
title: "CDS Final Project Group 3"
author: "Group 3"
date: "`r Sys.Date()`"
output: pdf_document
fontsize: 11pt
documentclass: article
geometry: margin=1in
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggplot2))
customer_churn <- read_csv("Customer-Churn-Records.csv", show_col_types = FALSE)
```

***

##LABS

```{r}
check_ratio <- function(counts) {
  total <- sum(counts)
  ratio <- max(counts) / total
  return(ratio >= 0.7)
}
```


```{r}
customer_churn <- customer_churn %>%
  mutate(
    Exited = recode(Exited, 
                    "0" = "No",
                    "1" = "Yes")
  )
```

```{r}
# Analysis for Age vs Exited
age_groups <- cut(customer_churn$Age, breaks = seq(15, 90, by = 5))
age_vs_exited <- customer_churn %>%
  mutate(AgeGroup = age_groups) %>%
  group_by(AgeGroup, Exited) %>%
  summarise(count = n(), .groups = "drop") %>%
  spread(Exited, count, fill = 0) %>%
  rowwise() %>%
  mutate(SignificantDifference = check_ratio(c_across(c("Yes", "No"))))
```

```{r}
# Analysis for Gender vs Exited
gender_vs_exited <- customer_churn %>%
  group_by(Gender, Exited) %>%
  summarise(count = n(), .groups = "drop") %>%
  spread(Exited, count, fill = 0) %>%
  rowwise() %>%
  mutate(SignificantDifference = check_ratio(c_across(c("Yes", "No"))))
```

```{r}
ggplot(customer_churn, aes(x = Age, fill = Exited)) +
  geom_histogram(binwidth = 5, position = "dodge") +
  labs(
    title = "Histogram of Age Distribution by Exited Status",
    x = "Age",
    y = "Count",
    fill = "Exited Status"
  ) +
  theme_minimal()
```

```{r}
# Histogram-like bar plot for Gender vs Exited
gender_vs_exited <- customer_churn %>%
  group_by(Gender, Exited) %>%
  summarise(count = n(), .groups = 'drop')

ggplot(gender_vs_exited, aes(x = Gender, y = count, fill = Exited)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Bar Plot of Gender Distribution by Exited Status",
    x = "Gender",
    y = "Count",
    fill = "Exited Status"
  ) +
  theme_minimal()
```
```{r}
customer_churn <- customer_churn %>%
  mutate(Age = cut(Age, breaks = c(0, 15, 30, 45, 60, 100), 
                         labels = c("0-15", "16-30", "31-45", "46-60", "60+")))
```

```{r}
ggplot(customer_churn, aes(x = Age, fill = Exited)) +
  geom_bar(binwidth = 5, position = "dodge") +
  labs(
    title = "Histogram of Age(Binded by 15 Years) Distribution by Exited Status",
    x = "Age(Binded by 15 Years)",
    y = "Count",
    fill = "Exited Status"
  ) +
  theme_minimal()
```